# Generated by Django 5.2.5 on 2025-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0002_alter_likepage_og_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="likepage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="likepage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="likespageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="likespageindex",
            name="og_image",
        ),
    ]
