# Generated by Django 5.2.4 on 2025-07-10 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("likes", "0002_likespageindex_canonical_url_likespageindex_og_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="likepage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="likepage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="likespageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="likespageindex",
            name="og_image",
        ),
    ]
