# Generated by Django 5.2.3 on 2025-06-22 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientpage",
            name="name",
        ),
    ]
