# Generated by Django 5.2.3 on 2025-06-22 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_remove_clientpage_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientpage",
            old_name="url",
            new_name="client_url",
        ),
    ]
