# Generated by Django 5.2.3 on 2025-06-22 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_rename_url_clientpage_client_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientindexpage",
            name="intro",
        ),
    ]
