# Generated by Django 5.2.3 on 2025-06-22 09:23

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0004_remove_clientindexpage_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientpage",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Show this project prominently",
                verbose_name="Featured Project",
            ),
        ),
        migrations.AddField(
            model_name="clientpage",
            name="project_type",
            field=models.CharField(
                blank=True,
                help_text="e.g., E-commerce, Corporate Website, Web App",
                max_length=100,
                verbose_name="Project Type",
            ),
        ),
        migrations.AddField(
            model_name="clientpage",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="e.g., Full-Stack Developer, Frontend Developer, Lead Developer",
                max_length=100,
                verbose_name="My Position/Role",
            ),
        ),
        migrations.AddField(
            model_name="clientpage",
            name="short_description",
            field=models.TextField(
                blank=True,
                help_text="Brief description for project listings",
                max_length=200,
                verbose_name="Short Description",
            ),
        ),
        migrations.AddField(
            model_name="clientpage",
            name="technologies",
            field=models.CharField(
                blank=True,
                help_text="e.g., Django, React, PostgreSQL (comma-separated)",
                max_length=200,
                verbose_name="Technologies Used",
            ),
        ),
        migrations.AlterField(
            model_name="clientpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("image", 1),
                    ("quote", 2),
                    ("heading", 5),
                    ("embed", 6),
                    ("gallery", 7),
                    ("code", 8),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select a heading size"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                                ("h5", "H5"),
                                ("h6", "H6"),
                            ],
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 3), ("size", 4)]],
                        {},
                    ),
                    6: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    7: ("wagtail.blocks.ListBlock", (1,), {"label": "Image Gallery"}),
                    8: ("wagtail.blocks.TextBlock", (), {"label": "Code Snippet"}),
                },
            ),
        ),
    ]
