# Generated by Django 5.2.3 on 2025-06-22 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0005_clientpage_is_featured_clientpage_project_type_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientpage",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="clientpage",
            name="page_ptr",
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True)),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Show in homepage marquee"
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ClientIndexPage",
        ),
        migrations.DeleteModel(
            name="ClientPage",
        ),
    ]
