# Generated by Django 5.2.3 on 2025-06-23 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0007_client_latest_revision"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="latest_revision",
        ),
    ]
