# Generated by Django 5.2.3 on 2025-06-27 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="postpage",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Leave blank to use the page's URL.",
                max_length=255,
                verbose_name="Canonical URL",
            ),
        ),
        migrations.AddField(
            model_name="postpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Preview image",
            ),
        ),
    ]
