# Generated by Django 5.2.3 on 2025-07-01 15:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0014_alter_postpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("note", 5),
                    ("article", 7),
                    ("reply", 12),
                    ("like", 15),
                    ("repost", 18),
                    ("bookmark", 22),
                    ("photo", 26),
                    ("video", 29),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "blockquote", "hr"],
                            "help_text": "Write your note content. Supports rich text formatting like bold, italic, and links",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Paste a direct link to your video from YouTube, Vimeo, or other platforms",
                            "label": "Video URL (YouTube, Vimeo, etc.)",
                        },
                    ),
                    2: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {
                            "help_text": "Upload and select a video file from your media library"
                        },
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Choose an image from your media library to display alongside content"
                        },
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("video_embed", 1), ("video", 2), ("image", 3)]],
                        {
                            "help_text": "Optional: Add images or videos to accompany your note",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 0), ("media", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the main title for your article",
                            "required": True,
                        },
                    ),
                    7: ("wagtail.blocks.StructBlock", [[("title", 6)]], {}),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL of the original post you're replying to",
                            "required": True,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title of the post you're replying to (for reference)",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional: Description of the target page content",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Write your reply. This will be linked to the original post",
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("in_reply_to", 8),
                                ("reply_title", 9),
                                ("description", 10),
                                ("content", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL of the content you want to like (supports IndieWeb 'like-of' microformat)",
                            "required": True,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Title of the content you're liking",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("like_of", 13), ("title", 14), ("description", 10)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL of the original content you want to share with your audience",
                            "required": True,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Title of the content you're reposting",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("repost_of", 16), ("title", 17), ("description", 10)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL of the page you want to bookmark for later reference",
                            "required": True,
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Title of the bookmarked content",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional: Your personal notes about why you're bookmarking this",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("bookmark_of", 19),
                                ("title", 20),
                                ("description", 10),
                                ("notes", 21),
                            ]
                        ],
                        {},
                    ),
                    23: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    24: (
                        "wagtail.blocks.ListBlock",
                        (23,),
                        {
                            "help_text": "Add one or more photos. Click '+ Add Photo' to include multiple images",
                            "label": "Photo(s)",
                            "min_num": 1,
                        },
                    ),
                    25: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional: Add a caption or description for your photo(s)",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("images", 24), ("caption", 25)]],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.StreamBlock",
                        [[("video_embed", 1), ("video", 2)]],
                        {
                            "help_text": "Add videos either by URL (YouTube/Vimeo) or upload from your media library",
                            "label": "Video(s)",
                            "required": True,
                        },
                    ),
                    28: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional: Add a caption or description for your video(s)",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("videos", 27), ("caption", 28)]],
                        {},
                    ),
                },
                default="article",
            ),
        ),
    ]
