# Generated by Django 5.2.3 on 2025-07-01 17:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0025_alter_postpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("note", 5),
                    ("article", 14),
                    ("reply", 19),
                    ("like", 22),
                    ("repost", 25),
                    ("bookmark", 29),
                    ("photo", 33),
                    ("video", 36),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "blockquote", "hr"],
                            "help_text": "Write your note content. Supports rich text formatting like bold, italic, and links",
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Paste a direct link to your video from YouTube, Vimeo, or other platforms",
                            "label": "Video URL (YouTube, Vimeo, etc.)",
                        },
                    ),
                    2: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {
                            "help_text": "Upload and select a video file from your media library"
                        },
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Choose an image from your media library to display alongside content"
                        },
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("video_embed", 1), ("video", 2), ("image", 3)]],
                        {
                            "help_text": "Optional: Add images or videos to accompany your note",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 0), ("media", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.TextBlock", (), {}),
                    7: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "help_text": "Write your article content. Use headings (H2, H3) to structure your text",
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("python", "Python"),
                                ("javascript", "JavaScript"),
                                ("typescript", "TypeScript"),
                                ("html", "HTML"),
                                ("css", "CSS"),
                                ("json", "JSON"),
                                ("bash", "Bash"),
                                ("sql", "SQL"),
                                ("php", "PHP"),
                                ("java", "Java"),
                                ("cpp", "C++"),
                                ("csharp", "C#"),
                                ("ruby", "Ruby"),
                                ("go", "Go"),
                                ("rust", "Rust"),
                                ("yaml", "YAML"),
                                ("xml", "XML"),
                                ("markdown", "Markdown"),
                            ],
                            "help_text": "Select the programming language for syntax highlighting",
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("andromeeda", "Andromeeda"),
                                ("aurora-x", "Aurora X"),
                                ("ayu-dark", "Ayu Dark"),
                                ("catppuccin-frappe", "Catppuccin Frappé"),
                                ("catppuccin-latte", "Catppuccin Latte"),
                                ("catppuccin-macchiato", "Catppuccin Macchiato"),
                                ("catppuccin-mocha", "Catppuccin Mocha"),
                                ("dark-plus", "Dark Plus"),
                                ("dracula", "Dracula Theme"),
                                ("dracula-soft", "Dracula Theme Soft"),
                                ("everforest-dark", "Everforest Dark"),
                                ("everforest-light", "Everforest Light"),
                                ("github-dark", "GitHub Dark"),
                                ("github-dark-default", "GitHub Dark Default"),
                                ("github-dark-dimmed", "GitHub Dark Dimmed"),
                                (
                                    "github-dark-high-contrast",
                                    "GitHub Dark High Contrast",
                                ),
                                ("github-light", "GitHub Light"),
                                ("github-light-default", "GitHub Light Default"),
                                (
                                    "github-light-high-contrast",
                                    "GitHub Light High Contrast",
                                ),
                                ("gruvbox-dark-hard", "Gruvbox Dark Hard"),
                                ("gruvbox-dark-medium", "Gruvbox Dark Medium"),
                                ("gruvbox-dark-soft", "Gruvbox Dark Soft"),
                                ("gruvbox-light-hard", "Gruvbox Light Hard"),
                                ("gruvbox-light-medium", "Gruvbox Light Medium"),
                                ("gruvbox-light-soft", "Gruvbox Light Soft"),
                                ("houston", "Houston"),
                                ("kanagawa-dragon", "Kanagawa Dragon"),
                                ("kanagawa-lotus", "Kanagawa Lotus"),
                                ("kanagawa-wave", "Kanagawa Wave"),
                                ("laserwave", "LaserWave"),
                                ("light-plus", "Light Plus"),
                                ("material-theme", "Material Theme"),
                                ("material-theme-darker", "Material Theme Darker"),
                                ("material-theme-lighter", "Material Theme Lighter"),
                                ("material-theme-ocean", "Material Theme Ocean"),
                                (
                                    "material-theme-palenight",
                                    "Material Theme Palenight",
                                ),
                                ("min-dark", "Min Dark"),
                                ("min-light", "Min Light"),
                                ("monokai", "Monokai"),
                                ("night-owl", "Night Owl"),
                                ("nord", "Nord"),
                                ("one-dark-pro", "One Dark Pro"),
                                ("one-light", "One Light"),
                                ("plastic", "Plastic"),
                                ("poimandres", "Poimandres"),
                                ("red", "Red"),
                                ("rose-pine", "Rosé Pine"),
                                ("rose-pine-dawn", "Rosé Pine Dawn"),
                                ("rose-pine-moon", "Rosé Pine Moon"),
                                ("slack-dark", "Slack Dark"),
                                ("slack-ochin", "Slack Ochin"),
                                ("snazzy-light", "Snazzy Light"),
                                ("solarized-dark", "Solarized Dark"),
                                ("solarized-light", "Solarized Light"),
                                ("synthwave-84", "Synthwave '84"),
                                ("tokyo-night", "Tokyo Night"),
                                ("vesper", "Vesper"),
                                ("vitesse-black", "Vitesse Black"),
                                ("vitesse-dark", "Vitesse Dark"),
                                ("vitesse-light", "Vitesse Light"),
                            ],
                            "help_text": "Select the color theme for syntax highlighting",
                        },
                    ),
                    10: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Enter your code here", "widget": ()},
                    ),
                    11: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Auto-generated highlighted HTML (do not edit manually)",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("language", 8),
                                ("theme", 9),
                                ("code", 10),
                                ("highlighted_html", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 7), ("image", 3), ("codeblock", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("summary", 6), ("featured_image", 3), ("body", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL of the original post you're replying to",
                            "required": True,
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title of the post you're replying to (for reference)",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional: Description of the target page content",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Write your reply. This will be linked to the original post",
                            "required": True,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("in_reply_to", 15),
                                ("reply_title", 16),
                                ("description", 17),
                                ("content", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL of the content you want to like (supports IndieWeb 'like-of' microformat)",
                            "required": True,
                        },
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Title of the content you're liking",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("like_of", 20), ("title", 21), ("description", 17)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL of the original content you want to share with your audience",
                            "required": True,
                        },
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Title of the content you're reposting",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("repost_of", 23), ("title", 24), ("description", 17)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL of the page you want to bookmark for later reference",
                            "required": True,
                        },
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional: Title of the bookmarked content",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional: Your personal notes about why you're bookmarking this",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("bookmark_of", 26),
                                ("title", 27),
                                ("description", 17),
                                ("notes", 28),
                            ]
                        ],
                        {},
                    ),
                    30: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    31: (
                        "wagtail.blocks.ListBlock",
                        (30,),
                        {
                            "help_text": "Add one or more photos. Click '+ Add Photo' to include multiple images",
                            "label": "Photo(s)",
                            "min_num": 1,
                        },
                    ),
                    32: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional: Add a caption or description for your photo(s)",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("images", 31), ("caption", 32)]],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.StreamBlock",
                        [[("video_embed", 1), ("video", 2)]],
                        {
                            "help_text": "Add videos either by URL (YouTube/Vimeo) or upload from your media library",
                            "label": "Video(s)",
                            "required": True,
                        },
                    ),
                    35: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional: Add a caption or description for your video(s)",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("videos", 34), ("caption", 35)]],
                        {},
                    ),
                },
                default="article",
            ),
        ),
    ]
