services:
  django:
    image: myapp-django
    entrypoint: ["/app/bin/django-entrypoint.sh"]
    networks:
      - maw-django-network

  celery:
    image: myapp-django
    command:
      - celery
      - '-A'
      - src.tasks
      - worker
      - '-l'
      - INFO
      - '--without-gossip'
      - '--without-mingle'
      - '--without-heartbeat'
    networks:
      - maw-django-network
    depends_on:
      - django

  celery_beat:
    image: myapp-django
    command:
      - celery
      - '-A'
      - src.tasks
      - beat
      - '-l'
      - INFO
      - '--scheduler'
      - 'django_celery_beat.schedulers:DatabaseScheduler'
    networks:
      - maw-django-network
    depends_on:
      - django

  nginx:
    image: myapp-nginx
    networks:
      - maw-django-network
    depends_on:
      - django

networks:
  maw-django-network:
    name: coolify
    external: true
