title: Mahmoud Ashraf
description: Mahmoud Ashraf is a Front-end developer based in Alexandria, Egypt.
keywords:
  - blog
  - front-end
  - javascript
  - linux
author: Mahmoud Ashraf
base_url: https://maw.sh
locale: en-US
app_css: /css/app.css
social:
  twitter: https://twitter.com/maw_sh
  mastodon: https://fosstodon.org/\@22mahmoud
  fediverse: \@22mahmoud@fosstodon.org
  youtube: https://www.youtube.com/\@22mahmoud
  reddit: https://reddit.com/user/22mahmoud_
  pixelfed: https://pixelfed.social/i/web/profile/201636586306277376
  github: https://github.com/22mahmoud
last_webmention_sync: "2024-08-21T15:38:44Z"
