providers = ["python", "node"]

[phases.build]
cmds = [
  "pnpm install",
  "pnpm build",
  "mkdir staticfiles",
  "cp static/manifest.json staticfiles",
  "python manage.py collectstatic --noinput",
]

[start]
cmd = "python manage.py migrate && gunicorn config.wsgi"
