providers = ["python", "node"]

[phases."python:post"]
dependsOn = ['node:build']
cmds = [
  "python manage.py collectstatic --noinput --clear --verbosity 2",
  "python manage.py migrate --noinput",
]

[start]
cmd = "./scripts/start"
