# Generated by Django 5.2.3 on 2025-06-26 15:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

import src.base.blocks.link


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(blank=True, help_text="Text to describe the page"),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 22),
                            ("clients", 23),
                            ("social_links", 24),
                            ("Video", 25),
                            ("button", 10),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Hero image", "required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": True},
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link"]},
                            ),
                            3: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ]
                                },
                            ),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("sm", "Small"),
                                        ("md", "Medium"),
                                        ("lg", "Large"),
                                    ]
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Optional icon name", "required": False},
                            ),
                            6: ("wagtail.blocks.CharBlock", (), {"max_length": 20}),
                            7: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            8: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            9: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"required": False},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("button_type", 3),
                                        ("size", 4),
                                        ("button_icon", 5),
                                        ("button_text", 6),
                                        ("external_link", 7),
                                        ("internal_link", 8),
                                        ("download_link", 9),
                                    ]
                                ],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": src.base.blocks.link.get_available_social_choices
                                },
                            ),
                            12: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("sm", "Small"),
                                        ("md", "Medium"),
                                        ("lg", "Large"),
                                    ],
                                    "required": False,
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("platform", 11), ("size", 12)]],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("default", "Default Link"),
                                        ("icon", "Icon Only"),
                                    ],
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Specify title for external link or provide override title for internal/download/pages links.",
                                    "label": "Link Title Text",
                                    "required": False,
                                },
                            ),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Specify title for screen Reader in case you use only icons",
                                    "label": "Screen Reader Link Text",
                                    "required": False,
                                },
                            ),
                            17: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Use to link to selected internal page OR...",
                                    "label": "Link (Internal Page)",
                                    "required": False,
                                },
                            ),
                            18: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {
                                    "help_text": "Use to link to selected document for download OR",
                                    "label": "Download (Document)",
                                    "required": False,
                                },
                            ),
                            19: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Use to link to an external site.",
                                    "label": "Link (External URL)",
                                    "required": False,
                                },
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("link_type", 14),
                                        ("size", 12),
                                        ("text", 15),
                                        ("sr_text", 16),
                                        ("icon", 5),
                                        ("internal_link", 17),
                                        ("download_link", 18),
                                        ("external_link", 19),
                                    ]
                                ],
                                {},
                            ),
                            21: (
                                "wagtail.blocks.StreamBlock",
                                [[("site", 13), ("custom", 20)]],
                                {"required": False},
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 0),
                                        ("headline", 1),
                                        ("text", 2),
                                        ("cta", 10),
                                        ("social_links", 21),
                                    ]
                                ],
                                {},
                            ),
                            23: (
                                "src.clients.blocks.ClientsMarqueeStaticBlock",
                                (),
                                {},
                            ),
                            24: (
                                "wagtail.blocks.StreamBlock",
                                [[("site", 13), ("custom", 20)]],
                                {},
                            ),
                            25: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                        },
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Preview image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avilable_for_projects",
                    models.BooleanField(
                        default=False, verbose_name="Avilable for projects"
                    ),
                ),
                ("twitter", models.CharField(blank=True, verbose_name="Twitter")),
                ("mastodon", models.CharField(blank=True, verbose_name="Mastodon")),
                ("youtube", models.CharField(blank=True, verbose_name="Youtube")),
                ("reddit", models.CharField(blank=True, verbose_name="Reddit")),
                ("github", models.CharField(blank=True, verbose_name="Github")),
                (
                    "pixelfed",
                    models.CharField(blank=True, verbose_name="Pixelfed.social"),
                ),
                ("linkedin", models.CharField(blank=True, verbose_name="Linkedin")),
                ("bluesky", models.CharField(blank=True, verbose_name="Bluesky")),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
