# Generated by Django 5.2.3 on 2025-06-27 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_person"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "person", "verbose_name_plural": "people"},
        ),
    ]
