# Generated by Django 5.2.3 on 2025-06-18 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_sitesettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteSettings",
        ),
    ]
