# Generated by Django 5.2.3 on 2025-06-19 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_delete_sitesettings"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_suffix",
                    models.CharField(
                        default="Mahmoud Ashraf",
                        help_text="The suffix for the title meta tag e.g. ' | The Wagtail Bakery'",
                        max_length=255,
                        verbose_name="Title suffix",
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Twitter Account Handle"
                    ),
                ),
                (
                    "mastdon",
                    models.URLField(blank=True, verbose_name="Mastdon Account URL"),
                ),
                (
                    "youtube",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Youtube Account Handle"
                    ),
                ),
                (
                    "reddit",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Reddit Account Handle"
                    ),
                ),
                (
                    "github",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Github Account Handle"
                    ),
                ),
                (
                    "pixelfed",
                    models.URLField(blank=True, verbose_name="Pixelfed Account URL"),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
