# Generated by Django 5.2.3 on 2025-06-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_person_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Check this to make this person the default author for new posts",
                verbose_name="Default author",
            ),
        ),
    ]
