# Generated by Django 5.2.3 on 2025-06-27 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_person_is_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="is_default",
        ),
    ]
