# Generated by Django 5.2.3 on 2025-06-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_sitesettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="mastdon",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bluesky",
            field=models.CharField(blank=True, verbose_name="Bluesky"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="fosstodon",
            field=models.URLField(blank=True, verbose_name="Fosstodon"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="github",
            field=models.CharField(blank=True, verbose_name="Github"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="pixelfed",
            field=models.CharField(blank=True, verbose_name="Pixelfed.social"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="reddit",
            field=models.CharField(blank=True, verbose_name="Reddit"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="twitter",
            field=models.CharField(blank=True, verbose_name="Twitter"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="youtube",
            field=models.CharField(blank=True, verbose_name="Youtube"),
        ),
    ]
