# Generated by Django 5.2.4 on 2025-07-15 21:00

import wagtail.fields
from django.db import migrations

import src.base.blocks.link


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_genericpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 22),
                    ("clients", 23),
                    ("social_links", 24),
                    ("Video", 25),
                    ("button", 12),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hero image", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("muted", "Muted"),
                                ("disabled", "Disabled"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Icon to display before the text.",
                            "label": "Prefix Icon",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Icon to display after the text.",
                            "label": "Suffix Icon",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "For an icon-only button. Overrides prefix/suffix icons.",
                            "label": "Icon-Only",
                            "required": False,
                        },
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"max_length": 20}),
                    9: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    10: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    11: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("type", 3),
                                ("size", 4),
                                ("prefix_icon_name", 5),
                                ("suffix_icon_name", 6),
                                ("icon_name", 7),
                                ("text", 8),
                                ("external_link", 9),
                                ("internal_link", 10),
                                ("download_link", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": src.base.blocks.link.get_available_social_choices},
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ],
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("platform", 13), ("size", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Prefix Icon", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Suffix Icon", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "For an icon-only link. Overrides prefix/suffix icons.",
                            "label": "Icon-Only",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 16),
                                ("prefix_icon", 17),
                                ("suffix_icon", 18),
                                ("icon", 19),
                                ("size", 4),
                                ("external_link", 9),
                                ("internal_link", 10),
                                ("download_link", 11),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 15), ("custom", 20)]],
                        {"required": False},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("headline", 1),
                                ("text", 2),
                                ("cta", 12),
                                ("social_links", 21),
                            ]
                        ],
                        {},
                    ),
                    23: ("src.clients.blocks.ClientsMarqueeStaticBlock", (), {}),
                    24: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 15), ("custom", 20)]],
                        {},
                    ),
                    25: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                },
            ),
        ),
    ]
