# Generated by Django 5.2.3 on 2025-06-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_remove_person_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=255, null=True, unique=True
            ),
        ),
    ]
