# Generated by Django 5.2.3 on 2025-06-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_remove_sitesettings_mastdon_sitesettings_bluesky_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="fosstodon",
            field=models.CharField(blank=True, verbose_name="Fosstodon"),
        ),
    ]
