# Generated by Django 5.2.3 on 2025-06-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_person_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
