# Generated by Django 5.2.3 on 2025-06-19 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_alter_sitesettings_fosstodon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="title_suffix",
        ),
    ]
