# Generated by Django 5.2.3 on 2025-06-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_alter_person_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="bio",
            field=models.CharField(blank=True, max_length=254, verbose_name="bio"),
        ),
        migrations.AddField(
            model_name="person",
            name="title",
            field=models.CharField(blank=True, max_length=254, verbose_name="Title"),
        ),
    ]
