# Generated by Django 5.2.3 on 2025-06-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_person_bio_person_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="bio",
            field=models.TextField(blank=True, max_length=254, verbose_name="Bio"),
        ),
    ]
