# Generated by Django 5.2.3 on 2025-06-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_genericpage_canonical_url_genericpage_og_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="avilable_for_projects",
            field=models.BooleanField(
                default=False, verbose_name="Avilable for projects"
            ),
        ),
    ]
