# Generated by Django 5.2.5 on 2025-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_genericpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericpage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="genericpage",
            name="og_image",
        ),
    ]
