# Generated by Django 5.2.4 on 2025-07-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_person_email_person_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericpage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="genericpage",
            name="og_image",
        ),
    ]
