# Generated by Django 5.2.3 on 2025-06-21 09:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_sitesettings_avilable_for_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hero image", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Contact", "max_length": 255, "required": False},
                    ),
                    4: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("headline", 1),
                                ("text", 2),
                                ("cta", 3),
                                ("cta_link", 4),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
