# Generated by Django 5.2.3 on 2025-06-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_genericpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="linkedin",
            field=models.CharField(blank=True, verbose_name="Linkedin"),
        ),
    ]
