# Generated by Django 5.2.5 on 2025-08-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_genericpage_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Name of the webring", max_length=255),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji or small text icon, e.g. 🌐",
                        max_length=10,
                    ),
                ),
                ("link", models.URLField(help_text="Main webring URL")),
                ("description", models.TextField(blank=True)),
                (
                    "previous_link",
                    models.URLField(
                        blank=True, help_text="URL to previous site in the webring"
                    ),
                ),
                (
                    "next_link",
                    models.URLField(
                        blank=True, help_text="URL to next site in the webring"
                    ),
                ),
            ],
            options={
                "verbose_name": "Webring",
                "verbose_name_plural": "Webrings",
                "ordering": ["title"],
            },
        ),
    ]
