# Generated by Django 5.2.4 on 2025-07-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_genericpage_repeat_in_subnav_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericpage",
            name="repeat_in_subnav",
        ),
        migrations.RemoveField(
            model_name="genericpage",
            name="repeated_item_text",
        ),
    ]
