# Generated by Django 5.2.3 on 2025-06-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0018_alter_genericpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="fosstodon",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mastodon",
            field=models.CharField(blank=True, verbose_name="Mastodon"),
        ),
    ]
