# Generated by Django 5.2.3 on 2025-06-23 20:24

import src.base.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_remove_sitesettings_fosstodon_sitesettings_mastodon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 8), ("clients", 9), ("social_links", 10), ("Video", 11)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hero image", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Contact", "max_length": 255, "required": False},
                    ),
                    4: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": src.base.blocks.link.get_available_social_choices},
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("platform", 5)]], {}),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 6)]],
                        {"required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("headline", 1),
                                ("text", 2),
                                ("cta", 3),
                                ("cta_link", 4),
                                ("social_links", 7),
                            ]
                        ],
                        {},
                    ),
                    9: ("src.clients.blocks.ClientsMarqueeStaticBlock", (), {}),
                    10: ("wagtail.blocks.StreamBlock", [[("site", 6)]], {}),
                    11: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                },
            ),
        ),
    ]
