# Generated by Django 5.2.3 on 2025-06-23 20:29

import src.base.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0021_alter_genericpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 15), ("clients", 16), ("social_links", 17), ("Video", 18)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hero image", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Contact", "max_length": 255, "required": False},
                    ),
                    4: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": src.base.blocks.link.get_available_social_choices},
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("platform", 5)]], {}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to display for the link",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional icon name", "required": False},
                    ),
                    9: ("wagtail.blocks.PageChooserBlock", (), {"label": "Page Link"}),
                    10: ("wagtail.blocks.URLBlock", (), {"label": "External URL"}),
                    11: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "Document Link"},
                    ),
                    12: (
                        "wagtail.blocks.StreamBlock",
                        [[("page", 9), ("url", 10), ("document", 11)]],
                        {"label": "Link (page, URL, or document)", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("icon", 8), ("link", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 6), ("custom", 13)]],
                        {"required": False},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("headline", 1),
                                ("text", 2),
                                ("cta", 3),
                                ("cta_link", 4),
                                ("social_links", 14),
                            ]
                        ],
                        {},
                    ),
                    16: ("src.clients.blocks.ClientsMarqueeStaticBlock", (), {}),
                    17: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 6), ("custom", 13)]],
                        {},
                    ),
                    18: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                },
            ),
        ),
    ]
