# Generated by Django 5.2.3 on 2025-06-24 09:26

import src.base.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0026_alter_genericpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 14), ("clients", 15), ("social_links", 16), ("Video", 17)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hero image", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Contact", "max_length": 255, "required": False},
                    ),
                    4: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": src.base.blocks.get_available_social_choices},
                    ),
                    6: ("wagtail.blocks.StreamBlock", [[("platform", 5)]], {}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Specify title for external link or provide override title for internal/download/pages links.",
                            "label": "Link Title Text",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional icon name", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Use to link to selected internal page OR...",
                            "label": "Link (Internal Page)",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use to link to selected document for download OR",
                            "label": "Download (Document)",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use to link to an external site.",
                            "label": "Link (External URL)",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 7),
                                ("icon", 8),
                                ("internal_link", 9),
                                ("download_link", 10),
                                ("external_link", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 6), ("custom", 12)]],
                        {"required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("headline", 1),
                                ("text", 2),
                                ("cta", 3),
                                ("cta_link", 4),
                                ("social_links", 13),
                            ]
                        ],
                        {},
                    ),
                    15: ("src.clients.blocks.ClientsMarqueeStaticBlock", (), {}),
                    16: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 6), ("custom", 12)]],
                        {},
                    ),
                    17: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                },
            ),
        ),
    ]
