# Generated by Django 5.2.3 on 2025-06-24 16:19

import src.base.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0030_alter_genericpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 15),
                    ("clients", 16),
                    ("social_links", 17),
                    ("Video", 18),
                    ("button", 23),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hero image", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Contact", "max_length": 255, "required": False},
                    ),
                    4: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": src.base.blocks.link.get_available_social_choices},
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("platform", 5)]], {}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Specify title for external link or provide override title for internal/download/pages links.",
                            "label": "Link Title Text",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Specify title for screen Reader in case you use only icons",
                            "label": "Screen Reader Link Text",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional icon name", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Use to link to selected internal page OR...",
                            "label": "Link (Internal Page)",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use to link to selected document for download OR",
                            "label": "Download (Document)",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use to link to an external site.",
                            "label": "Link (External URL)",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 7),
                                ("sr_text", 8),
                                ("icon", 9),
                                ("internal_link", 10),
                                ("download_link", 11),
                                ("external_link", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 6), ("custom", 13)]],
                        {"required": False},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("headline", 1),
                                ("text", 2),
                                ("cta", 3),
                                ("cta_link", 4),
                                ("social_links", 14),
                            ]
                        ],
                        {},
                    ),
                    16: ("src.clients.blocks.ClientsMarqueeStaticBlock", (), {}),
                    17: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 6), ("custom", 13)]],
                        {},
                    ),
                    18: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                            ]
                        },
                    ),
                    20: ("wagtail.blocks.CharBlock", (), {"max_length": 20}),
                    21: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    22: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_type", 19),
                                ("button_icon", 9),
                                ("button_text", 20),
                                ("external_link", 21),
                                ("internal_link", 4),
                                ("download_link", 22),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
