# Generated by Django 5.2.3 on 2025-06-25 08:41

import src.base.blocks.link
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0035_alter_genericpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 22),
                    ("clients", 23),
                    ("social_links", 24),
                    ("Video", 25),
                    ("button", 10),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hero image", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional icon name", "required": False},
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"max_length": 20}),
                    7: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    8: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_type", 3),
                                ("size", 4),
                                ("button_icon", 5),
                                ("button_text", 6),
                                ("external_link", 7),
                                ("internal_link", 8),
                                ("download_link", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": src.base.blocks.link.get_available_social_choices},
                    ),
                    12: ("wagtail.blocks.StructBlock", [[("platform", 11)]], {}),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default Link"),
                                ("icon", "Icon Only"),
                                ("nav_active", "Nav Active"),
                                ("nav_inactive", "Nav Inactive"),
                            ],
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ],
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Specify title for external link or provide override title for internal/download/pages links.",
                            "label": "Link Title Text",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Specify title for screen Reader in case you use only icons",
                            "label": "Screen Reader Link Text",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Use to link to selected internal page OR...",
                            "label": "Link (Internal Page)",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use to link to selected document for download OR",
                            "label": "Download (Document)",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use to link to an external site.",
                            "label": "Link (External URL)",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 13),
                                ("size", 14),
                                ("text", 15),
                                ("sr_text", 16),
                                ("icon", 5),
                                ("internal_link", 17),
                                ("download_link", 18),
                                ("external_link", 19),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 12), ("custom", 20)]],
                        {"required": False},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("headline", 1),
                                ("text", 2),
                                ("cta", 10),
                                ("social_links", 21),
                            ]
                        ],
                        {},
                    ),
                    23: ("src.clients.blocks.ClientsMarqueeStaticBlock", (), {}),
                    24: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 12), ("custom", 20)]],
                        {},
                    ),
                    25: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                },
            ),
        ),
    ]
