# Generated by Django 5.2.4 on 2025-07-30 18:38

import django.db.models.deletion
import modelcluster.contrib.taggit
import src.pagination.mixins
import src.posts.mixins
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "legacy_url_path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The full path of the URL from the old static site (e.g., /blog/old-slug).",
                        max_length=512,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("note", 5)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "blockquote",
                                        "hr",
                                    ],
                                    "help_text": (
                                        "Write your note content.",
                                        "Supports rich text formatting like bold, italic, and links",
                                    ),
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "Paste a direct link to your video from YouTube, Vimeo, or other platforms",
                                    "label": "Video URL (YouTube, Vimeo, etc.)",
                                },
                            ),
                            2: (
                                "wagtailmedia.blocks.VideoChooserBlock",
                                (),
                                {
                                    "help_text": "Upload and select a video file from your media library"
                                },
                            ),
                            3: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Choose an image from your media library to display alongside content"
                                },
                            ),
                            4: (
                                "wagtail.blocks.StreamBlock",
                                [[("video_embed", 1), ("video", 2), ("image", 3)]],
                                {
                                    "help_text": "Optional: Add images or videos to accompany your note",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("content", 0), ("media", 4)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Preview image",
                    ),
                ),
                (
                    "tags",
                    modelcluster.contrib.taggit.ClusterTaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="base.PageTag",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(src.posts.mixins.SinglePostMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="NotesPageIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(blank=True, help_text="Text to describe the page"),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Preview image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                src.pagination.mixins.PaginatedArchiveMixin,
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
    ]
