# Generated by Django 5.2.4 on 2025-07-10 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_notespageindex_canonical_url_notespageindex_og_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notespage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="notespage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="notespageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="notespageindex",
            name="og_image",
        ),
    ]
