# Generated by Django 5.2.4 on 2025-07-24 15:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_notespage_legacy_url_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notespage",
            name="body",
            field=wagtail.fields.StreamField(
                [("note", 5)],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "blockquote", "hr"],
                            "help_text": (
                                "Write your note content.",
                                "Supports rich text formatting like bold, italic, and links",
                            ),
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Paste a direct link to your video from YouTube, Vimeo, or other platforms",
                            "label": "Video URL (YouTube, Vimeo, etc.)",
                        },
                    ),
                    2: (
                        "wagtailmedia.blocks.VideoChooserBlock",
                        (),
                        {
                            "help_text": "Upload and select a video file from your media library"
                        },
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Choose an image from your media library to display alongside content"
                        },
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("video_embed", 1), ("video", 2), ("image", 3)]],
                        {
                            "help_text": "Optional: Add images or videos to accompany your note",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 0), ("media", 4)]],
                        {},
                    ),
                },
            ),
        ),
    ]
