# Generated by Django 5.2.5 on 2025-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_alter_notespage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notespage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="notespage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="notespageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="notespageindex",
            name="og_image",
        ),
    ]
