# Generated by Django 5.2.5 on 2025-08-15 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0003_auto_20250805_1355"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchListIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="WatchItemPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "tmdb_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="TMDb ID for Movie/TV (leave blank if not in TMDb)",
                        null=True,
                    ),
                ),
                (
                    "watch_type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("tv", "TV Show"),
                            ("short", "Short Film"),
                            ("play", "Play / Theatre"),
                        ],
                        default="movie",
                        max_length=20,
                    ),
                ),
                (
                    "watch_status",
                    models.CharField(
                        choices=[
                            ("watching", "Currently Watching"),
                            ("completed", "Completed"),
                            ("planned", "Plan to Watch"),
                            ("abandoned", "Abandoned / Dropped"),
                        ],
                        default="watching",
                        max_length=20,
                    ),
                ),
                ("watch_date", models.DateField(blank=True, null=True)),
                ("overview", models.TextField(blank=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("personal_note", models.TextField(blank=True)),
                (
                    "poster_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
