# Generated by Django 5.2.5 on 2025-08-15 21:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0002_watchitempage_canonical_url_watchitempage_og_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchitempage",
            name="personal_note",
        ),
        migrations.AddField(
            model_name="watchitempage",
            name="content",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Write your note content. Supports rich text formatting like bold, italic, and links",
            ),
        ),
    ]
