# Generated by Django 5.2.5 on 2025-08-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0003_remove_watchitempage_personal_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchitempage",
            name="tmdb_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="TMDb ID for Movie/TV", null=True
            ),
        ),
        migrations.AlterField(
            model_name="watchitempage",
            name="watch_type",
            field=models.CharField(
                choices=[("movie", "Movie"), ("tv", "TV Show")],
                default="movie",
                max_length=20,
            ),
        ),
    ]
