# Generated by Django 5.2.4 on 2025-07-30 18:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webmention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wm_id", models.BigIntegerField(unique=True)),
                ("wm_source", models.URLField(max_length=1024)),
                ("wm_target", models.URLField(max_length=1024)),
                ("wm_protocol", models.CharField(max_length=50)),
                ("wm_received", models.DateTimeField()),
                ("wm_property", models.CharField(max_length=50)),
                ("wm_private", models.BooleanField(default=False)),
                ("url", models.URLField(blank=True, max_length=1024, null=True)),
                ("published", models.DateTimeField(blank=True, null=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebmentionSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Webmention Sync State",
            },
        ),
        migrations.CreateModel(
            name="BookmarkWebmention",
            fields=[
                (
                    "webmention_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="webmentions.webmention",
                    ),
                ),
                ("bookmark_of", models.URLField(max_length=1024)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("webmentions.webmention",),
        ),
        migrations.CreateModel(
            name="LikeWebmention",
            fields=[
                (
                    "webmention_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="webmentions.webmention",
                    ),
                ),
                ("like_of", models.URLField(max_length=1024)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("webmentions.webmention",),
        ),
        migrations.CreateModel(
            name="MentionWebmention",
            fields=[
                (
                    "webmention_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="webmentions.webmention",
                    ),
                ),
                ("mention_of", models.URLField(max_length=1024)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("webmentions.webmention",),
        ),
        migrations.CreateModel(
            name="ReplyWebmention",
            fields=[
                (
                    "webmention_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="webmentions.webmention",
                    ),
                ),
                ("in_reply_to", models.URLField(max_length=1024)),
                ("content_text", models.TextField(blank=True)),
                ("content_html", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("webmentions.webmention",),
        ),
        migrations.CreateModel(
            name="RepostWebmention",
            fields=[
                (
                    "webmention_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="webmentions.webmention",
                    ),
                ),
                ("repost_of", models.URLField(max_length=1024)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("webmentions.webmention",),
        ),
        migrations.CreateModel(
            name="RSVPWebmention",
            fields=[
                (
                    "webmention_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="webmentions.webmention",
                    ),
                ),
                (
                    "rsvp",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("maybe", "Maybe"),
                            ("interested", "Interested"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("webmentions.webmention",),
        ),
        migrations.CreateModel(
            name="WebmentionAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="webmention",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webmentions",
                to="webmentions.webmentionauthor",
            ),
        ),
        migrations.AddIndex(
            model_name="webmention",
            index=models.Index(
                fields=["wm_property", "wm_target"],
                name="webmentions_wm_prop_6b37fa_idx",
            ),
        ),
    ]
