# Generated by Django 5.2.4 on 2025-07-09 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webmention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wm_id", models.BigIntegerField(unique=True)),
                ("wm_source", models.URLField()),
                ("wm_target", models.URLField()),
                ("wm_protocol", models.CharField(max_length=50)),
                ("wm_received", models.DateTimeField()),
                ("wm_property", models.CharField(max_length=50)),
                ("wm_private", models.BooleanField(default=False)),
                ("url", models.URLField(blank=True, null=True)),
                ("published", models.DateTimeField(blank=True, null=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="WebmentionAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("photo", models.URLField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookmarkWebmention",
            fields=[
                (
                    "webmention_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="webmentions.webmention",
                    ),
                ),
                ("bookmark_of", models.URLField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("webmentions.webmention",),
        ),
        migrations.CreateModel(
            name="LikeWebmention",
            fields=[
                (
                    "webmention_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="webmentions.webmention",
                    ),
                ),
                ("like_of", models.URLField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("webmentions.webmention",),
        ),
        migrations.CreateModel(
            name="MentionWebmention",
            fields=[
                (
                    "webmention_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="webmentions.webmention",
                    ),
                ),
                ("mention_of", models.URLField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("webmentions.webmention",),
        ),
        migrations.CreateModel(
            name="ReplyWebmention",
            fields=[
                (
                    "webmention_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="webmentions.webmention",
                    ),
                ),
                ("in_reply_to", models.URLField()),
                ("content_text", models.TextField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("webmentions.webmention",),
        ),
        migrations.CreateModel(
            name="RepostWebmention",
            fields=[
                (
                    "webmention_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="webmentions.webmention",
                    ),
                ),
                ("repost_of", models.URLField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("webmentions.webmention",),
        ),
        migrations.CreateModel(
            name="RSVPWebmention",
            fields=[
                (
                    "webmention_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="webmentions.webmention",
                    ),
                ),
                (
                    "rsvp",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("maybe", "Maybe"),
                            ("interested", "Interested"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("webmentions.webmention",),
        ),
        migrations.AddField(
            model_name="webmention",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webmentions",
                to="webmentions.webmentionauthor",
            ),
        ),
    ]
