# Generated by Django 5.2.4 on 2025-07-09 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("webmentions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebmentionSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Webmention Sync State",
            },
        ),
        migrations.AlterField(
            model_name="webmentionauthor",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
