# Generated by Django 5.2.4 on 2025-07-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webmentions", "0002_webmentionsync_alter_webmentionauthor_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmarkwebmention",
            name="bookmark_of",
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="likewebmention",
            name="like_of",
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="mentionwebmention",
            name="mention_of",
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="replywebmention",
            name="in_reply_to",
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="repostwebmention",
            name="repost_of",
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="webmention",
            name="url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="webmention",
            name="wm_source",
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="webmention",
            name="wm_target",
            field=models.URLField(max_length=1024),
        ),
    ]
