# Generated by Django 5.2.4 on 2025-07-09 21:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webmentions", "0003_alter_bookmarkwebmention_bookmark_of_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replywebmention",
            name="content_text",
            field=wagtail.fields.RichTextField(),
        ),
    ]
