# Generated by Django 5.2.4 on 2025-07-09 21:33

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webmentions", "0004_alter_replywebmention_content_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="replywebmention",
            name="content_html",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="replywebmention",
            name="content_text",
            field=models.TextField(blank=True),
        ),
    ]
