# Generated by Django 5.2.4 on 2025-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("webmentions", "0005_replywebmention_content_html_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webmention",
            options={},
        ),
        migrations.AddIndex(
            model_name="webmention",
            index=models.Index(
                fields=["wm_property"], name="webmentions_wm_prop_a0bc36_idx"
            ),
        ),
    ]
