# Generated by Django 5.2.4 on 2025-07-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("webmentions", "0006_alter_webmention_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="webmention",
            name="webmentions_wm_prop_a0bc36_idx",
        ),
        migrations.AddIndex(
            model_name="webmention",
            index=models.Index(
                fields=["wm_property", "wm_target"],
                name="webmentions_wm_prop_6b37fa_idx",
            ),
        ),
    ]
