# Generated by Django 5.2.4 on 2025-08-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_auto_20250805_1355"),
        ("seo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seosettings",
            name="og_image_default",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown when linking to this page on social media. This can also be customized on each page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
                verbose_name="Default preview image",
            ),
        ),
    ]
