# Generated by Django 5.2.3 on 2025-06-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="mastdon_site",
            field=models.CharField(
                blank=True,
                help_text="The @username of the website owner’s Twitter handle.",
                max_length=16,
                verbose_name="Mastdon Account",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="twitter_site",
            field=models.CharField(
                blank=True,
                help_text="The @username of the website owner’s Twitter handle.",
                max_length=16,
                verbose_name="Twitter Account",
            ),
        ),
    ]
