# Generated by Django 5.2.4 on 2025-07-10 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seo", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SeoSettings",
        ),
    ]
