# Generated by Django 5.2.3 on 2025-06-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seo", "0003_sitespecificsocialmediasettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="mastdon_site",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="twitter_site",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="github",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Github Account Handle"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mastdon",
            field=models.URLField(blank=True, verbose_name="Mastdon Account URL"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="pixelfed",
            field=models.URLField(
                blank=True, max_length=16, verbose_name="Pixelfed Account URL"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="reddit",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Reddit Account Handle"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="twitter",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Twitter Account Handle"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube",
            field=models.CharField(
                blank=True, max_length=16, verbose_name="Youtube Account Handle"
            ),
        ),
        migrations.DeleteModel(
            name="SiteSpecificSocialMediaSettings",
        ),
    ]
