# Generated by Django 5.2.3 on 2025-06-19 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seo", "0004_remove_sitesettings_mastdon_site_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteSettings",
        ),
    ]
