# Generated by Django 5.2.3 on 2025-06-19 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seo", "0005_delete_sitesettings"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_suffix",
                    models.CharField(
                        default="Mahmoud Ashraf",
                        help_text="The suffix for the title meta tag e.g. ' | The Wagtail Bakery'",
                        max_length=255,
                        verbose_name="Title suffix",
                    ),
                ),
                (
                    "og_image_default",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shown when linking to this page on social media. This can also be customized on each page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Default preview image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
