# Generated by Django 5.2.3 on 2025-06-19 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seo", "0006_seosettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SeoMetaFields",
        ),
    ]
