# Generated by Django 5.2.4 on 2025-07-10 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="og_image",
        ),
    ]
