# Generated by Django 5.2.3 on 2025-06-20 18:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_text",
            field=wagtail.fields.RichTextField(help_text="Write A Hero body text"),
        ),
    ]
