# Generated by Django 5.2.4 on 2025-08-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_homepage_body"),
        ("images", "0003_auto_20250805_1355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
                verbose_name="Preview image",
            ),
        ),
    ]
