# Generated by Django 5.2.4 on 2025-08-07 12:21

import src.base.blocks.link
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 22),
                    ("clients", 23),
                    ("social_links", 24),
                    ("Video", 25),
                    ("button", 12),
                    ("flex_layout", 38),
                    ("featured_blog", 34),
                    ("feed", 36),
                    ("spacer", 40),
                    ("contact_form", 41),
                    ("featured_projects", 42),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hero image", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("muted", "Muted"),
                                ("disabled", "Disabled"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Icon to display before the text.",
                            "label": "Prefix Icon",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Icon to display after the text.",
                            "label": "Suffix Icon",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "For an icon-only button. Overrides prefix/suffix icons.",
                            "label": "Icon-Only",
                            "required": False,
                        },
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"max_length": 20}),
                    9: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    10: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    11: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("type", 3),
                                ("size", 4),
                                ("prefix_icon_name", 5),
                                ("suffix_icon_name", 6),
                                ("icon_name", 7),
                                ("text", 8),
                                ("external_link", 9),
                                ("internal_link", 10),
                                ("download_link", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": src.base.blocks.link.get_available_social_choices},
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ],
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("platform", 13), ("size", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Prefix Icon", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Suffix Icon", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "For an icon-only link. Overrides prefix/suffix icons.",
                            "label": "Icon-Only",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 16),
                                ("prefix_icon", 17),
                                ("suffix_icon", 18),
                                ("icon", 19),
                                ("size", 4),
                                ("external_link", 9),
                                ("internal_link", 10),
                                ("download_link", 11),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 15), ("custom", 20)]],
                        {"required": False},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("headline", 1),
                                ("text", 2),
                                ("cta", 12),
                                ("social_links", 21),
                            ]
                        ],
                        {},
                    ),
                    23: ("src.clients.blocks.ClientsMarqueeStaticBlock", (), {}),
                    24: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 15), ("custom", 20)]],
                        {},
                    ),
                    25: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("gap-2", "Small"),
                                ("gap-4", "Medium"),
                                ("gap-6", "Large"),
                                ("gap-8", "Extra\xa0Large"),
                            ],
                            "label": "Gap between items",
                        },
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Stack <\xa0640\u202fpx (sm)"),
                                ("md", "Stack <\xa0768\u202fpx (md)"),
                                ("lg", "Stack <\xa01024\u202fpx (lg)"),
                                ("xl", "Never stack – always row"),
                            ],
                            "help_text": "Choose the breakpoint where items switch from stacked (vertical) to inline (horizontal).",
                            "label": "Responsive behaviour",
                        },
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("start", "Left/Start"),
                                ("center", "Center"),
                                ("end", "Right/End"),
                                ("between", "Space\xa0Between"),
                                ("around", "Space\xa0Around"),
                                ("evenly", "Space\xa0Evenly"),
                            ],
                            "label": "Horizontal alignment",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("start", "Top/Start"),
                                ("center", "Center"),
                                ("end", "Bottom/End"),
                                ("stretch", "Stretch"),
                            ],
                            "label": "Vertical alignment",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "For design‑system power users. Space‑separated list, no leading dot.",
                            "label": "Additional CSS classes",
                            "required": False,
                        },
                    ),
                    31: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    32: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["articles.ArticlePage"]},
                    ),
                    33: ("wagtail.blocks.ListBlock", (32,), {}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 31), ("posts", 33)]],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "help_text": "Number of recent posts to show"},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 31), ("limit", 35)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("link", 20),
                                ("social", 15),
                                ("button", 12),
                                ("hero", 22),
                                ("featured_blog", 34),
                                ("feed", 36),
                            ]
                        ],
                        {"label": "Child blocks"},
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("gap", 26),
                                ("responsive", 27),
                                ("horizontal_align", 28),
                                ("vertical_align", 29),
                                ("extra_class", 30),
                                ("content", 37),
                            ]
                        ],
                        {},
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                                ("xl", "Extra Large"),
                            ],
                            "help_text": "Select a predefined amount of vertical space to add.",
                            "label": "Spacer Size",
                        },
                    ),
                    40: ("wagtail.blocks.StructBlock", [[("size", 39)]], {}),
                    41: ("src.contact.blocks.ContactFormStaticBlock", (), {}),
                    42: ("src.projects.blocks.FeaturedProjectsStaticBlock", (), {}),
                },
            ),
        ),
    ]
