# Generated by Django 5.2.4 on 2025-07-15 15:22

import wagtail.fields
from django.db import migrations

import src.base.blocks.link


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 22),
                    ("clients", 23),
                    ("social_links", 24),
                    ("Video", 25),
                    ("button", 10),
                    ("flex_layout", 38),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hero image", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("muted", "Muted"),
                                ("disabled", "Disabled"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional icon name", "required": False},
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"max_length": 20}),
                    7: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    8: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_type", 3),
                                ("size", 4),
                                ("button_icon", 5),
                                ("button_text", 6),
                                ("external_link", 7),
                                ("internal_link", 8),
                                ("download_link", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": src.base.blocks.link.get_available_social_choices},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ],
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("platform", 11), ("size", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default Link"),
                                ("icon", "Icon Only"),
                            ],
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Specify title for external link or provide override title for internal/download/pages links.",
                            "label": "Link Title Text",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Specify title for screen Reader in case you use only icons",
                            "label": "Screen Reader Link Text",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Use to link to selected internal page OR...",
                            "label": "Link (Internal Page)",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use to link to selected document for download OR",
                            "label": "Download (Document)",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use to link to an external site.",
                            "label": "Link (External URL)",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 14),
                                ("size", 12),
                                ("text", 15),
                                ("sr_text", 16),
                                ("icon", 5),
                                ("internal_link", 17),
                                ("download_link", 18),
                                ("external_link", 19),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 13), ("custom", 20)]],
                        {"required": False},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("headline", 1),
                                ("text", 2),
                                ("cta", 10),
                                ("social_links", 21),
                            ]
                        ],
                        {},
                    ),
                    23: ("src.clients.blocks.ClientsMarqueeStaticBlock", (), {}),
                    24: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 13), ("custom", 20)]],
                        {},
                    ),
                    25: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("gap-2", "Small"),
                                ("gap-4", "Medium"),
                                ("gap-6", "Large"),
                                ("gap-8", "Extra\xa0Large"),
                            ],
                            "label": "Gap between items",
                        },
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Stack <\xa0640\u202fpx (sm)"),
                                ("md", "Stack <\xa0768\u202fpx (md)"),
                                ("lg", "Stack <\xa01024\u202fpx (lg)"),
                                ("xl", "Never stack – always row"),
                            ],
                            "help_text": "Choose the breakpoint where items switch from stacked (vertical) to inline (horizontal).",
                            "label": "Responsive behaviour",
                        },
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("start", "Left/Start"),
                                ("center", "Center"),
                                ("end", "Right/End"),
                                ("between", "Space\xa0Between"),
                                ("around", "Space\xa0Around"),
                                ("evenly", "Space\xa0Evenly"),
                            ],
                            "label": "Horizontal alignment",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("start", "Top/Start"),
                                ("center", "Center"),
                                ("end", "Bottom/End"),
                                ("stretch", "Stretch"),
                            ],
                            "label": "Vertical alignment",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "For design‑system power users. Space‑separated list, no leading dot.",
                            "label": "Additional CSS classes",
                            "required": False,
                        },
                    ),
                    31: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    32: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["articles.ArticlePage"]},
                    ),
                    33: ("wagtail.blocks.ListBlock", (32,), {}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 31), ("posts", 33)]],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "help_text": "Number of recent posts to show"},
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 31), ("limit", 35)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("link", 20),
                                ("social", 13),
                                ("button", 10),
                                ("hero", 22),
                                ("featured_blog", 34),
                                ("feed", 36),
                            ]
                        ],
                        {"label": "Child blocks"},
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("gap", 26),
                                ("responsive", 27),
                                ("horizontal_align", 28),
                                ("vertical_align", 29),
                                ("extra_class", 30),
                                ("content", 37),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
