# Generated by Django 5.2.5 on 2025-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_homepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="og_image",
        ),
    ]
