# Generated by Django 5.2.4 on 2025-07-15 20:42

import wagtail.fields
from django.db import migrations

import src.base.blocks.link


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 25),
                    ("clients", 26),
                    ("social_links", 27),
                    ("Video", 28),
                    ("button", 12),
                    ("flex_layout", 41),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hero image", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": True},
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("muted", "Muted"),
                                ("disabled", "Disabled"),
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Icon to display before the text.",
                            "label": "Prefix Icon",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Icon to display after the text.",
                            "label": "Suffix Icon",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "For an icon-only button. Overrides prefix/suffix icons.",
                            "label": "Icon-Only",
                            "required": False,
                        },
                    ),
                    8: ("wagtail.blocks.CharBlock", (), {"max_length": 20}),
                    9: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    10: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    11: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("type", 3),
                                ("size", 4),
                                ("prefix_icon_name", 5),
                                ("suffix_icon_name", 6),
                                ("icon_name", 7),
                                ("text", 8),
                                ("external_link", 9),
                                ("internal_link", 10),
                                ("download_link", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": src.base.blocks.link.get_available_social_choices},
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ],
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("platform", 13), ("size", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default Link"),
                                ("icon", "Icon Only"),
                            ],
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Specify title for external link or provide override title for internal/download/pages links.",
                            "label": "Link Title Text",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Specify title for screen Reader in case you use only icons",
                            "label": "Screen Reader Link Text",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Optional icon name", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Use to link to selected internal page OR...",
                            "label": "Link (Internal Page)",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use to link to selected document for download OR",
                            "label": "Download (Document)",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use to link to an external site.",
                            "label": "Link (External URL)",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 16),
                                ("size", 14),
                                ("text", 17),
                                ("sr_text", 18),
                                ("icon", 19),
                                ("internal_link", 20),
                                ("download_link", 21),
                                ("external_link", 22),
                            ]
                        ],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 15), ("custom", 23)]],
                        {"required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("headline", 1),
                                ("text", 2),
                                ("cta", 12),
                                ("social_links", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("src.clients.blocks.ClientsMarqueeStaticBlock", (), {}),
                    27: (
                        "wagtail.blocks.StreamBlock",
                        [[("site", 15), ("custom", 23)]],
                        {},
                    ),
                    28: ("wagtailmedia.blocks.VideoChooserBlock", (), {}),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("gap-2", "Small"),
                                ("gap-4", "Medium"),
                                ("gap-6", "Large"),
                                ("gap-8", "Extra\xa0Large"),
                            ],
                            "label": "Gap between items",
                        },
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Stack <\xa0640\u202fpx (sm)"),
                                ("md", "Stack <\xa0768\u202fpx (md)"),
                                ("lg", "Stack <\xa01024\u202fpx (lg)"),
                                ("xl", "Never stack – always row"),
                            ],
                            "help_text": "Choose the breakpoint where items switch from stacked (vertical) to inline (horizontal).",
                            "label": "Responsive behaviour",
                        },
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("start", "Left/Start"),
                                ("center", "Center"),
                                ("end", "Right/End"),
                                ("between", "Space\xa0Between"),
                                ("around", "Space\xa0Around"),
                                ("evenly", "Space\xa0Evenly"),
                            ],
                            "label": "Horizontal alignment",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("start", "Top/Start"),
                                ("center", "Center"),
                                ("end", "Bottom/End"),
                                ("stretch", "Stretch"),
                            ],
                            "label": "Vertical alignment",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "For design‑system power users. Space‑separated list, no leading dot.",
                            "label": "Additional CSS classes",
                            "required": False,
                        },
                    ),
                    34: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    35: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["articles.ArticlePage"]},
                    ),
                    36: ("wagtail.blocks.ListBlock", (35,), {}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 34), ("posts", 36)]],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "help_text": "Number of recent posts to show"},
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 34), ("limit", 38)]],
                        {},
                    ),
                    40: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("link", 23),
                                ("social", 15),
                                ("button", 12),
                                ("hero", 25),
                                ("featured_blog", 37),
                                ("feed", 39),
                            ]
                        ],
                        {"label": "Child blocks"},
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("gap", 29),
                                ("responsive", 30),
                                ("horizontal_align", 31),
                                ("vertical_align", 32),
                                ("extra_class", 33),
                                ("content", 40),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
