# Generated by Django 5.2.4 on 2025-07-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="repeat_in_subnav",
            field=models.BooleanField(
                default=False,
                help_text="If checked, a link to this page will be repeated alongside it's direct children when displaying a sub-navigation for this page.",
                verbose_name="repeat in sub-navigation",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="repeated_item_text",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'Section home' or 'Overview'. If left blank, the page title will be used.",
                max_length=255,
                verbose_name="repeated item link text",
            ),
        ),
    ]
