# Generated by Django 5.2.3 on 2025-07-04 16:26

import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models

import src.pagination.mixins
import src.posts.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideosPageIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(blank=True, help_text="Text to describe the page"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                src.pagination.mixins.PaginatedArchiveMixin,
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="VideoPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Leave blank to use the page's URL.",
                        max_length=255,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("video", 4)],
                        block_lookup={
                            0: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "Paste a direct link to your video from YouTube, Vimeo, or other platforms",
                                    "label": "Video URL (YouTube, Vimeo, etc.)",
                                },
                            ),
                            1: (
                                "wagtailmedia.blocks.VideoChooserBlock",
                                (),
                                {
                                    "help_text": "Upload and select a video file from your media library"
                                },
                            ),
                            2: (
                                "wagtail.blocks.StreamBlock",
                                [[("video_embed", 0), ("video", 1)]],
                                {
                                    "help_text": "Add videos either by URL (YouTube/Vimeo) or upload from your media library",
                                    "label": "Video(s)",
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "Optional: Add a caption or description for your video(s)",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("videos", 2), ("caption", 3)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Preview image",
                    ),
                ),
                (
                    "tags",
                    modelcluster.contrib.taggit.ClusterTaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="base.PageTag",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(src.posts.mixins.SinglePostMixin, "wagtailcore.page"),
        ),
    ]
