# Generated by Django 5.2.4 on 2025-07-10 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_videospageindex_canonical_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videopage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="videopage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="videospageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="videospageindex",
            name="og_image",
        ),
    ]
