# Generated by Django 5.2.5 on 2025-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_videopage_og_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videopage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="videopage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="videospageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="videospageindex",
            name="og_image",
        ),
    ]
