# Generated by Django 5.2.4 on 2025-07-30 18:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guestbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "emoji",
                    models.CharField(
                        help_text="Emoji representing mood or vibe", max_length=2
                    ),
                ),
                ("message", models.TextField(max_length=200)),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Optional link (e.g., social profile, site)",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("hidden", "Hidden"),
                        ],
                        default="public",
                        help_text="Control who can view this entry",
                        max_length=10,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("retro", "🕹️ Retro Wave"),
                            ("sunset", "🌅 Sunset Vibes"),
                            ("minimal", "🖤 Minimal"),
                            ("bright", "🎉 Bright Pop"),
                        ],
                        default="minimal",
                        help_text="Visual style preset for the card",
                        max_length=20,
                    ),
                ),
                (
                    "radius",
                    models.CharField(
                        choices=[
                            ("rounded-none", "None"),
                            ("rounded", "Slight"),
                            ("rounded-lg", "Large"),
                            ("rounded-xl", "Extra"),
                        ],
                        default="rounded",
                        help_text="Border radius of the card",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Guestbook Entry",
                "verbose_name_plural": "Guestbook Entries",
            },
        ),
        migrations.CreateModel(
            name="GuestbookFormPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Optional introduction/help text for the guestbook.",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("guestbook_form", 0)],
                        blank=True,
                        block_lookup={
                            0: ("src.guestbook.blocks.GuestbookFormStaticBlock", (), {})
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="GuestbookIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Optional introduction/help text for the guestbook.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
