# Generated by Django 5.2.4 on 2025-07-21 16:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guestbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "emoji",
                    models.CharField(
                        help_text="Emoji representing mood or vibe", max_length=2
                    ),
                ),
                ("message", models.TextField()),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Optional link (e.g., social profile, site)",
                    ),
                ),
                (
                    "sparkle",
                    models.BooleanField(
                        default=False, help_text="Should entry sparkle?"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("hidden", "Hidden"),
                        ],
                        default="public",
                        help_text="Control who can view this entry",
                        max_length=10,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="light",
                        max_length=10,
                    ),
                ),
                (
                    "bg",
                    models.CharField(
                        choices=[
                            ("bg-white", "White"),
                            ("bg-gradient-1", "Green"),
                            ("bg-gradient-2", "Yellow"),
                            ("bg-accent", "Accent"),
                            ("bg-darker", "Dark"),
                        ],
                        default="bg-white",
                        max_length=50,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        choices=[
                            ("text-black", "Black"),
                            ("text-white", "White"),
                            ("text-accent", "Accent"),
                        ],
                        default="text-black",
                        max_length=50,
                    ),
                ),
                (
                    "font",
                    models.CharField(
                        choices=[
                            ("font-sans", "Sans (Figtree)"),
                            ("font-serif", "Serif (Outfit)"),
                            ("font-mono", "Mono"),
                        ],
                        default="font-sans",
                        max_length=50,
                    ),
                ),
                (
                    "radius",
                    models.CharField(
                        choices=[
                            ("rounded", "Slight"),
                            ("rounded-lg", "Large"),
                            ("rounded-xl", "Extra"),
                            ("rounded-full", "Pill"),
                        ],
                        default="rounded",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Guestbook Entry",
                "verbose_name_plural": "Guestbook Entries",
            },
        ),
        migrations.CreateModel(
            name="GuestbookIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Optional introduction/help text for the guestbook.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
