# Generated by Django 5.2.4 on 2025-08-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestbook",
            name="message",
            field=models.TextField(
                help_text="Supports basic Markdown and HTML. Max 280 characters. GIFs allowed from giphy/tenor/imgur.",
                max_length=280,
            ),
        ),
    ]
