# Generated by Django 5.2.4 on 2025-07-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guestbook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestbook",
            name="message",
            field=models.TextField(max_length=200),
        ),
    ]
