# Generated by Django 5.2.4 on 2025-07-21 16:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guestbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestbookindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("guestbook_form", 0)],
                blank=True,
                block_lookup={
                    0: ("src.guestbook.blocks.GuestbookFormStaticBlock", (), {})
                },
            ),
        ),
    ]
