# Generated by Django 5.2.4 on 2025-08-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook", "0002_alter_guestbook_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestbook",
            name="message_html",
            field=models.TextField(blank=True, null=True),
        ),
    ]
