# Generated by Django 5.2.4 on 2025-07-21 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guestbook", "0002_guestbookindexpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guestbook",
            name="color",
        ),
    ]
