# Generated by Django 5.2.4 on 2025-07-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guestbook", "0002_alter_guestbook_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guestbook",
            name="bg",
        ),
        migrations.RemoveField(
            model_name="guestbook",
            name="font",
        ),
        migrations.RemoveField(
            model_name="guestbook",
            name="text",
        ),
        migrations.AddField(
            model_name="guestbook",
            name="style",
            field=models.CharField(
                choices=[
                    ("retro", "🕹️ Retro Wave"),
                    ("sunset", "🌅 Sunset Vibes"),
                    ("minimal", "🖤 Minimal"),
                    ("bright", "🎉 Bright Pop"),
                ],
                default="minimal",
                help_text="Visual style preset for the card",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="guestbook",
            name="radius",
            field=models.CharField(
                choices=[
                    ("rounded-none", "None"),
                    ("rounded", "Slight"),
                    ("rounded-lg", "Large"),
                    ("rounded-xl", "Extra"),
                ],
                default="rounded",
                help_text="Border radius of the card",
                max_length=20,
            ),
        ),
    ]
