# Generated by Django 5.2.4 on 2025-07-21 17:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guestbook", "0003_remove_guestbook_color"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestbookFormPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Optional introduction/help text for the guestbook.",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("guestbook_form", 0)],
                        blank=True,
                        block_lookup={
                            0: ("src.guestbook.blocks.GuestbookFormStaticBlock", (), {})
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.RemoveField(
            model_name="guestbookindexpage",
            name="body",
        ),
    ]
