# Generated by Django 5.2.4 on 2025-07-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guestbook", "0004_guestbookformpage_remove_guestbookindexpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestbook",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("hidden", "Hidden"),
                ],
                default="private",
                help_text="Control who can view this entry",
                max_length=10,
            ),
        ),
    ]
