# Generated by Django 5.2.4 on 2025-07-21 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guestbook", "0005_alter_guestbook_visibility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guestbook",
            name="sparkle",
        ),
    ]
