# Generated by Django 5.2.4 on 2025-07-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guestbook", "0006_remove_guestbook_sparkle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestbook",
            name="bg",
            field=models.CharField(
                choices=[
                    ("bg-white", "White"),
                    ("bg-sunset", "Sunset"),
                    ("bg-gradient-1", "Green"),
                    ("bg-gradient-2", "Yellow"),
                    ("bg-accent", "Accent"),
                    ("bg-darker", "Dark"),
                ],
                default="bg-white",
                max_length=50,
            ),
        ),
    ]
