# Generated by Django 5.2.4 on 2025-08-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook", "0006_alter_guestbook_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestbook",
            name="message",
            field=models.TextField(
                help_text="Supports basic Markdown and HTML. Max 300 characters. GIFs allowed from giphy/tenor/imgur.",
                max_length=2000,
            ),
        ),
    ]
