# Generated by Django 5.2.4 on 2025-08-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook", "0007_alter_guestbook_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestbook",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
