# Generated by Django 5.2.4 on 2025-08-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook", "0008_guestbook_pinned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestbook",
            name="pinned",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
