# Generated by Django 5.2.4 on 2025-07-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guestbook", "0008_alter_guestbook_font"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestbook",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("hidden", "Hidden"),
                ],
                default="public",
                help_text="Control who can view this entry",
                max_length=10,
            ),
        ),
    ]
