# Generated by Django 5.2.4 on 2025-07-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guestbook", "0009_alter_guestbook_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestbook",
            name="radius",
            field=models.CharField(
                choices=[
                    ("rounded-none", "None"),
                    ("rounded", "Slight"),
                    ("rounded-lg", "Large"),
                    ("rounded-xl", "Extra"),
                ],
                default="rounded",
                max_length=50,
            ),
        ),
    ]
