# Generated by Django 5.2.4 on 2025-07-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guestbook", "0010_alter_guestbook_radius"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestbook",
            name="font",
            field=models.CharField(
                choices=[
                    ("font-sans", "Sans"),
                    ("font-heading", "Heading"),
                    ("font-mono", "Mono"),
                ],
                default="font-sans",
                max_length=50,
            ),
        ),
    ]
