# Generated by Django 5.2.5 on 2025-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook", "0011_guestbookformpage_canonical_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guestbookformpage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="guestbookformpage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="guestbookindexpage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="guestbookindexpage",
            name="og_image",
        ),
    ]
