# Generated by Django 5.2.4 on 2025-07-10 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_articlespageindex_canonical_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlepage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="articlepage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="articlespageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="articlespageindex",
            name="og_image",
        ),
    ]
