# Generated by Django 5.2.5 on 2025-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_alter_articlepage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlepage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="articlepage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="articlespageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="articlespageindex",
            name="og_image",
        ),
    ]
