# Generated by Django 5.2.4 on 2025-07-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0024_articlepage_repeat_in_subnav_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlepage",
            name="repeat_in_subnav",
        ),
        migrations.RemoveField(
            model_name="articlepage",
            name="repeated_item_text",
        ),
        migrations.RemoveField(
            model_name="articlespageindex",
            name="repeat_in_subnav",
        ),
        migrations.RemoveField(
            model_name="articlespageindex",
            name="repeated_item_text",
        ),
    ]
