# Generated by Django 5.2.5 on 2025-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0002_alter_bookmarkpage_og_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmarkpage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="bookmarkpage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="bookmarkspageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="bookmarkspageindex",
            name="og_image",
        ),
    ]
