# Generated by Django 5.2.4 on 2025-07-10 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0002_bookmarkspageindex_canonical_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmarkpage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="bookmarkpage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="bookmarkspageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="bookmarkspageindex",
            name="og_image",
        ),
    ]
