# Generated by Django 5.2.5 on 2025-08-08 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0003_remove_bookmarkpage_canonical_url_and_more"),
        ("images", "0003_auto_20250805_1355"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmarkpage",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Leave blank to use the page's URL.",
                max_length=255,
                verbose_name="Canonical URL",
            ),
        ),
        migrations.AddField(
            model_name="bookmarkpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
                verbose_name="Preview image",
            ),
        ),
        migrations.AddField(
            model_name="bookmarkspageindex",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Leave blank to use the page's URL.",
                max_length=255,
                verbose_name="Canonical URL",
            ),
        ),
        migrations.AddField(
            model_name="bookmarkspageindex",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
                verbose_name="Preview image",
            ),
        ),
    ]
