# Generated by Django 5.2.4 on 2025-08-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="caption",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
