# Generated by Django 5.2.4 on 2025-08-05 13:55

from django.db import migrations

def migrate_images(apps, schema_editor):
    OldImage = apps.get_model("wagtailimages", "Image")
    NewImage = apps.get_model("images", "CustomImage")

    db_alias = schema_editor.connection.alias

    for old_image in OldImage.objects.using(db_alias).all():
        if not NewImage.objects.using(db_alias).filter(id=old_image.id).exists():
            NewImage.objects.using(db_alias).create(
                id=old_image.id,
                title=old_image.title,
                file=old_image.file,
                description=old_image.description,
                width=old_image.width,
                height=old_image.height,
                created_at=old_image.created_at,
                focal_point_x=old_image.focal_point_x,
                focal_point_y=old_image.focal_point_y,
                focal_point_width=old_image.focal_point_width,
                focal_point_height=old_image.focal_point_height,
                file_size=old_image.file_size,
                file_hash=old_image.file_hash,
                collection=old_image.collection,
                uploaded_by_user=old_image.uploaded_by_user,
                tags=old_image.tags.all(),
                caption="",
            )

class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_customimage_caption"),
    ]

    operations = [
        migrations.RunPython(migrate_images),
    ]
