# Generated by Django 5.2.5 on 2025-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reposts", "0002_alter_repostpage_og_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repostpage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="repostpage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="repostspageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="repostspageindex",
            name="og_image",
        ),
    ]
