# Generated by Django 5.2.4 on 2025-07-10 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reposts", "0002_repostspageindex_canonical_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repostpage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="repostpage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="repostspageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="repostspageindex",
            name="og_image",
        ),
    ]
