# Generated by Django 5.2.3 on 2025-07-04 16:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ProjectPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True, max_length=200, verbose_name="Short Description"
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Project Type"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="My Role"
                    ),
                ),
                (
                    "technologies",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Technologies Used"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured Project"),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("paragraph", 0),
                            ("image", 1),
                            ("quote", 2),
                            ("heading", 5),
                            ("embed", 6),
                            ("gallery", 7),
                            ("code", 8),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title", "required": True},
                            ),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "blank": True,
                                    "choices": [
                                        ("", "Select a heading size"),
                                        ("h1", "H1"),
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                        ("h5", "H5"),
                                        ("h6", "H6"),
                                    ],
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_text", 3), ("size", 4)]],
                                {},
                            ),
                            6: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                            7: (
                                "wagtail.blocks.ListBlock",
                                (1,),
                                {"label": "Image Gallery"},
                            ),
                            8: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Code Snippet"},
                            ),
                        },
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
