# Generated by Django 5.2.4 on 2025-08-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_auto_20250805_1355"),
        ("projects", "0002_alter_projectpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
