# Generated by Django 5.2.4 on 2025-07-13 14:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_projectpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("image", 1),
                    ("quote", 2),
                    ("heading", 5),
                    ("embed", 6),
                    ("gallery", 7),
                    ("code", 8),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "code"],
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select a heading size"),
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                                ("h5", "H5"),
                                ("h6", "H6"),
                            ],
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 3), ("size", 4)]],
                        {},
                    ),
                    6: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    7: ("wagtail.blocks.ListBlock", (1,), {"label": "Image Gallery"}),
                    8: ("wagtail.blocks.TextBlock", (), {"label": "Code Snippet"}),
                },
            ),
        ),
    ]
