# Generated by Django 5.2.4 on 2025-07-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_technology"),
        ("projects", "0006_alter_projectpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectpage",
            name="technologies",
        ),
        migrations.AddField(
            model_name="projectpage",
            name="technologies",
            field=models.ManyToManyField(blank=True, to="base.technology"),
        ),
    ]
