# Generated by Django 5.2.4 on 2025-08-04 21:09

from django.db import migrations

def clean_old_avatar_column(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE accounts_user
            SET avatar = NULL
            WHERE avatar = '';
        """)

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(clean_old_avatar_column),
    ]
