# Generated by Django 5.2.4 on 2025-08-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_old_avatar_alter_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="old_avatar",
        ),
    ]
