# Generated by Django 5.2.4 on 2025-07-10 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("replies", "0002_repliespageindex_canonical_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repliespageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="repliespageindex",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="replypage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="replypage",
            name="og_image",
        ),
    ]
