# Generated by Django 5.2.5 on 2025-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("replies", "0002_alter_repliespageindex_og_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repliespageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="repliespageindex",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="replypage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="replypage",
            name="og_image",
        ),
    ]
