# Generated by Django 5.2.4 on 2025-07-08 11:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0002_photospageindex_canonical_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photopage",
            name="body",
            field=wagtail.fields.StreamField(
                [("photo", 11)],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    1: (
                        "wagtail.blocks.ListBlock",
                        (0,),
                        {
                            "help_text": "Add one or more photos. Click '+ Add Photo' to include multiple images",
                            "label": "Photo(s)",
                            "min_num": 1,
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional: Add a caption or description for your photo(s)",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.DateTimeBlock",
                        (),
                        {
                            "help_text": "When was this photo taken?",
                            "label": "Date Taken",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Where was this photo taken? (City, place name, etc.)",
                            "label": "Location",
                            "required": False,
                        },
                    ),
                    5: ("wagtail.blocks.FloatBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("latitude", 5), ("longitude", 5)]],
                        {
                            "help_text": "Optional: Latitude and longitude of the photo's location",
                            "label": "GPS Coordinates",
                            "required": False,
                        },
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"label": "Person Tag"}),
                    8: (
                        "wagtail.blocks.ListBlock",
                        (7,),
                        {
                            "help_text": "Name or username of people in this photo",
                            "label": "People in Photo",
                            "required": False,
                        },
                    ),
                    9: ("wagtail.blocks.URLBlock", (), {"label": "Syndication URL"}),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {
                            "help_text": "Where else was this photo published (e.g. Flickr, Mastodon, etc.)",
                            "label": "Syndicated To",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("images", 1),
                                ("caption", 2),
                                ("taken_date", 3),
                                ("location", 4),
                                ("geo_coordinates", 6),
                                ("people", 8),
                                ("syndication", 10),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
