# Generated by Django 5.2.5 on 2025-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_alter_photopage_og_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photopage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="photopage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="photospageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="photospageindex",
            name="og_image",
        ),
    ]
