# Generated by Django 5.2.4 on 2025-07-08 17:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0003_alter_photopage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photopage",
            name="body",
            field=wagtail.fields.StreamField(
                [("photo", 5)],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    1: (
                        "wagtail.blocks.ListBlock",
                        (0,),
                        {
                            "help_text": "Add one or more photos. Click '+ Add Photo' to include multiple images",
                            "label": "Photo(s)",
                            "min_num": 1,
                        },
                    ),
                    2: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link"],
                            "help_text": "Optional: Add a caption or description for your photo(s)",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.DateTimeBlock",
                        (),
                        {
                            "help_text": "When was this photo taken?",
                            "label": "Date Taken",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Where was this photo taken? (City, place name, etc.)",
                            "label": "Location",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("images", 1),
                                ("caption", 2),
                                ("taken_date", 3),
                                ("location", 4),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
