# Generated by Django 5.2.4 on 2025-07-10 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0004_alter_photopage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photopage",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="photopage",
            name="og_image",
        ),
        migrations.RemoveField(
            model_name="photospageindex",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="photospageindex",
            name="og_image",
        ),
    ]
