# Generated by Django 5.2.5 on 2025-08-11 09:46

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_genericpage_tags"),
        ("photos", "0004_photopage_canonical_url_photopage_og_image_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="photospageindex",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="base.PageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
