# Generated by Django 5.2.4 on 2025-07-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0006_photopage_canonical_url_photopage_og_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photopage",
            name="legacy_url_path",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The full path of the URL from the old static site (e.g., /blog/old-slug).",
                max_length=512,
                null=True,
                unique=True,
            ),
        ),
    ]
