#!/bin/sh

file_path="src/index.md"
base_blog_dir="src/blog"
base_games_dir="src/games"
base_thoughts_dir="src/thoughts"
base_leetcode_dir="src/leetcode/problems"

blog_temp=$(mktemp)
blog_temp_sorted=$(mktemp)
playing_games_temp=$(mktemp)
completed_games_temp=$(mktemp)
completed_games_temp_sorted=$(mktemp)
thoughts_temp=$(mktemp)
thoughts_temp_sorted=$(mktemp)
leetcode_temp=$(mktemp)
leetcode_temp_sorted=$(mktemp)

for dir_name in "$base_blog_dir"/*/; do
	if [ -d "$dir_name" ]; then
		title=$(yq --front-matter=extract '.title-prefix' "$dir_name/index.md")
		date=$(yq --front-matter=extract '.date' "$dir_name/index.md")
		url=${dir_name#src/}

		echo "$date|$title|$url" >>"$blog_temp"
	fi
done

for dir_name in "$base_games_dir"/*/; do
	if [ -d "$dir_name" ]; then
		title=$(yq --front-matter=extract '.title' "$dir_name/index.md")
		date=$(yq --front-matter=extract '.date' "$dir_name/index.md")
		state=$(yq --front-matter=extract '.state' "$dir_name/index.md")
		url=${dir_name#src/}

		if [ "$state" = "active" ]; then
			echo "$date|$title|$state|$url" >>"$playing_games_temp"
		fi

		if [ "$state" = "completed" ]; then
			echo "$date|$title|$state|$url" >>"$completed_games_temp"
		fi
	fi
done

for dir_name in "$base_thoughts_dir"/*/; do
	if [ -d "$dir_name" ]; then
		date=$(yq --front-matter=extract '.date' "$dir_name/index.md")
		url=${dir_name#src/}
		content=$(sed '/^---$/,/^---$/d;' "$dir_name/index.md" | awk '{printf "%s\\n", $0}')

		echo "$date|$url|$content" >>"$thoughts_temp"
	fi
done

for dir_name in "$base_leetcode_dir"/*/; do
	if [ -d "$dir_name" ]; then
		title=$(yq --front-matter=extract '.title-prefix' "$dir_name/index.md")
		date=$(yq --front-matter=extract '.date' "$dir_name/index.md")
		url=${dir_name#src/}

		echo "$date|$title|$url" >>"$leetcode_temp"
	fi
done

sort -r "$blog_temp" | head -n 3 >"$blog_temp_sorted"
sort -r "$playing_games_temp" -o "$playing_games_temp"
sort -r "$completed_games_temp" | head -n 2 >"$completed_games_temp_sorted"
sort -r "$thoughts_temp" | head -n 3 >"$thoughts_temp_sorted"
sort -r "$leetcode_temp" | head -n 3 >"$leetcode_temp_sorted"

{
	cat <<EOF
---
title-prefix: Home
home: true
blogs:
EOF

	while IFS="|" read -r date title url; do
		cat <<EOF
  - title: $title
    url: /$url
    date: $date
EOF
	done <"$blog_temp_sorted"

	cat <<EOF
playing:
EOF

	while IFS="|" read -r date title state url; do
		cat <<EOF
  - title: $title
    date: $date
    url: /$url
EOF
	done <"$playing_games_temp"

	cat <<EOF
completed:
EOF

	while IFS="|" read -r date title state url; do
		cat <<EOF
  - title: $title
    date: $date
    url: /$url
EOF
	done <"$completed_games_temp_sorted"

	cat <<EOF
thoughts:
EOF

	while IFS="|" read -r date url content; do
		cat <<EOF
  - date: $date
    url: /$url
    content: |-
EOF
		echo "$content\n\s" | sed 's/\\n/\n/g' | sed 's/^/\t\t/'
	done <"$thoughts_temp_sorted"

	cat <<EOF
leetcode:
EOF

	while IFS="|" read -r date title url; do
		cat <<EOF
  - date: $date
    title: $title
    url: /$url
EOF
	done <"$leetcode_temp_sorted"

	cat <<EOF
header-includes: |-
  <style>
    br {
      display: none;
    }

    .section-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-top: 2.5em;
    }

    .section-header h3 {
      margin: 0;
    }

    .section-header a {
      display: flex;
      align-items: center;
      text-decoration: none;
      color: var(--c4);
    }

    .section-header a:hover {
      text-decoration: underline;
    }
    .thoughts ul {
      padding: 0;
    }

    .thoughts li {
      list-style-type: none;
      padding: 0;
    }

    .thoughts li {
      background-color: var(--c1);
      border: 1px solid var(--c5);
      border-radius: 8px;
      padding: 12px;
      margin-bottom: 16px;
      font-family: var(--sans);
      color: var(--c2);
    }

    .thoughts li div:first-of-type {
      margin-bottom: 10px;
    }

    .thoughts li a {
      color: var(--c3);
    }

    .thoughts li a:hover {
      color: var(--c4);
    }

    .thoughts li div {
      margin: 0;
      line-height: 1.6;
    }

    .blogs {
      display: flex;
      flex-direction: column;
      gap: 1rem;
      padding: 1rem;
      padding-left: 0;
    }

    .blog {
      background-color: var(--c5);
      border: 1px solid var(--c6);
      padding: 1rem;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      display: flex;
      flex-direction: column;
    }

    .blog-title {
      font-weight: bold;
      margin-bottom: 0.5rem;
    }

    .blog-date {
      font-size: 0.9rem;
      color: var(--c4);
      margin-bottom: 0.5rem;
    }

    .blog a {
      text-decoration: none;
      color: inherit;
    }

    .blog a:hover {
      text-decoration: underline;
    }

    .games {
      display: flex;
      flex-wrap: wrap;
      gap: 1rem;
      padding: 1rem;
      padding-left: 0;
    }

    .game {
      position: relative;
      background-color: var(--c5);
      border: 1px solid var(--c6);
      overflow: hidden;
      width: 150px;
      height: 240px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      display: flex;
      flex-direction: column;
    }

    .game img {
      width: 100%;
      height: 90px;
      display: block;
      object-fit: cover;
    }

    .game a {
      position: absolute;
      inset: 0;
      width: 100%;
      height: 100%;
    }

    .game-info {
      padding: 0.5rem;
      text-align: left;
      display: flex;
      flex-direction: column;
      flex-grow: 1;
    }

    .game-info span {
      color: var(--c2);
    }

    .game-info img {
      margin-right: 0.5rem;
      width: 18px;
      height: 18px;
      filter: invert(1);
      margin: 0;
    }

    .game-title {
      font-weight: bold;
      display: block;
      flex: 1;
    }

    .footer {
      margin-top: auto;
      display: flex;
      flex-direction: column;
      gap: 4px;
    }

    .game-date, .game-state {
      font-size: 0.9rem;
      color: var(--c4);
      display: flex;
      align-items: center;
      gap: 4px;
    }

    .game-playing {
      border-color: var(--status-active);
    }

    .game-completed {
      border-color: var(--status-completed);
    }
  </style>
---

### Welcome to My Space on the Internet

Hi, I'm **Mahmoud Ashraf** 👋.  
Based in **Alexandria, Egypt**, I'm a **Software Engineer** who makes websites.
I write about **Tech, Linux, Privacy, and Front-end Development**.  
Instead of using social media, I share my **posts and photos** here.  

[Learn More About Me](/about)
EOF
} >"$file_path"

rm "$blog_temp" "$blog_temp_sorted" "$playing_games_temp" "$completed_games_temp" "$completed_games_temp_sorted" "$thoughts_temp" "$thoughts_temp_sorted" "$leetcode_temp" "$leetcode_temp_sorted"

echo "src/index.md file generated successfully."
