#!/bin/bash

base_dir="src/blog"
final_content=""
temp_file=$(mktemp)
sorted_file=$(mktemp)

for dir_name in "$base_dir"/*/; do
	if [ -d "$dir_name" ]; then
		title=$(yq --front-matter=extract '.title-prefix' "$dir_name/index.md")
		date=$(yq --front-matter=extract '.date' "$dir_name/index.md")

		dir_name=${dir_name//src/}

		echo "$date|$title|$dir_name" >>"$temp_file"
	fi
done

sort "$temp_file" >"$sorted_file"

while IFS="|" read -r iso_date title dir_name; do
	date=$(date -d "$iso_date" "+%b %d, %Y")
	final_content=$(printf "%s\n%s" "- $date: [$title]($dir_name)  " "$final_content")
done <"$sorted_file"

rm "$temp_file" "$sorted_file"

cat <<EOF >src/blog/index.md
---
title-prefix: Blog
---

# Blog

_Subscribe via [RSS](https://maw.sh/rss.xml)_


$(printf "%s" "$final_content")
EOF

echo "blog/index.md file generated successfully."
