#!/bin/bash

base_dir="src/blog"
final_content=""
temp_file=$(mktemp)
sorted_file=$(mktemp)

for dir_name in "$base_dir"/*/; do
  if [ -d "$dir_name" ]; then
    title=$(yq --front-matter=extract '.title-prefix' "$dir_name/index.md")
    formated_date=$(yq --front-matter=extract '.date' "$dir_name/index.md")
    date=$(date -d "$formated_date" +%s)

		dir_name=${dir_name//src/}

    echo "$date|$formated_date|$title|$dir_name" >>"$temp_file"
  fi
done

sort "$temp_file" >"$sorted_file"

while IFS="|" read -r _ date title dir_name; do
  final_content=$(printf "%s\n%s" "- $date: [$title]($dir_name)  " "$final_content")
done <"$sorted_file"

rm "$temp_file" "$sorted_file"

cat <<EOF >src/blog/index.md
---
title-prefix: Blog
---

# Blog

_Subscribe via [RSS](https://maw.sh/rss.xml)_


$(printf "%s" "$final_content")
EOF

echo "blog/index.md file generated successfully."
