providers = ["python", "node"]

[phases.setup]
nixPkgs = ['...', 'imagemagick', 'imagemagick.dev']

[phases."python:post"]
dependsOn = ['node:build']
cmds = [
  "uv run python manage.py collectstatic --noinput --clear --verbosity 2",
  "uv run python manage.py migrate --noinput",
]

[start]
cmd = "./scripts/start"
