#!/bin/sh

gunicorn config.wsgi \
  --workers 5 \
  --bind 0.0.0.0:8000 \
  --worker-class sync \
  --timeout 60 \
  --access-logfile - \
  --error-logfile - \
  --log-level info \
  --max-requests 1000 \
  --max-requests-jitter 100
