#!/bin/sh

mkdir staticfiles
cp ./static/manifest.json staticfiles

python manage.py collectstatic --noinput
python manage.py migrate --noinput

gunicorn config.wsgi \
  --workers 5 \
  --bind 0.0.0.0:8000 \
  --worker-class sync \
  --timeout 60 \
  --access-logfile - \
  --error-logfile - \
  --log-level info \
  --max-requests 1000 \
  --max-requests-jitter 100
