name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: instal deps
        env:
          pandoc_url: https://github.com/jgm/pandoc/releases/download/3.1.8/pandoc-3.1.8-linux-amd64.tar.gz
          pandoc: pandoc-3.1.8
          pandoc_linux: pandoc-3.1.8-linux-amd64.tar.gz
        run: |
          sudo apt install imagemagick ffmpeg
          wget $pandoc_url
          tar -xvf $pandoc_linux
          sudo cp -r $pandoc/bin/* /usr/local/bin
          sudo cp -r $pandoc/share/* /usr/local/share

      - name: Checkout the source repository
        uses: actions/checkout@v3

      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .tmp
          key: ${{ runner.os }}-primes

      - name: build
        run: |
          make clean
          make build -j$(nproc)

      - name: Save Primes
        id: cache-primes-save
        uses: actions/cache/save@v4
        with:
          path: |
            .tmp
          key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}

      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: "placeholder"
          if_key_exists: fail 

      - name: add known_hosts
        run: ssh-keyscan -p ${{ secrets.PORT }} -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: rsync over SSH
        env:
          SSH_PORT: ${{ secrets.PORT }}
          SSH_USERNAME: ${{ secrets.USERNAME }}
          SSH_HOST: ${{ secrets.HOST }}
        run: |
          rsync -avz -e "ssh -p $SSH_PORT" dist $SSH_USERNAME@$SSH_HOST:~/website
