name: build

on:
  workflow_dispatch:
  push:
  workflow_run:
    workflows: ['update_webmentions']
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: instal deps
        env:
          pandoc_url: https://github.com/jgm/pandoc/releases/download/3.2.1/pandoc-3.2.1-linux-amd64.tar.gz
          pandoc: pandoc-3.2.1
          pandoc_linux: pandoc-3.2.1-linux-amd64.tar.gz
        run: |
          wget $pandoc_url; sudo apt install ffmpeg imagemagick
          sudo ln -s /usr/bin/convert /usr/bin/magick
          tar -xvf $pandoc_linux
          sudo cp -r $pandoc/bin/* /usr/local/bin
          sudo cp -r $pandoc/share/* /usr/local/share

      - name: Checkout the source repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .tmp
            dist
          key: ${{ runner.os }}-tmp-${{ github.sha }}

      - name: clean dist dir
        if: github.event_name == 'workflow_dispatch'
        run: make distclean

      - uses: actions/setup-node@v4
        with:
          node-version: '20.15.0'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: install node deps
        run: |
          npm install

      - name: build
        run: |
          make build -j$(nproc)

      - name: Save Primes
        id: cache-primes-save
        uses: actions/cache/save@v4
        with:
          path: |
            .tmp
            dist
          key: ${{ runner.os }}-tmp-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-tmp-

      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: "placeholder"
          if_key_exists: fail

      - name: add known_hosts
        run: ssh-keyscan -p ${{ secrets.PORT }} -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: rsync over SSH
        env:
          ssh_port: ${{ secrets.PORT }}
          ssh_username: ${{ secrets.USERNAME }}
          ssh_host: ${{ secrets.HOST }}
          build_path: ${{ secrets.BUILD_PATH }}
        run: |
          rsync -avz -e "ssh -p $ssh_port" dist $ssh_username@$ssh_host:$build_path
