name: build

on:
  workflow_dispatch:
  push:
  workflow_run:
    workflows: ['update_webmentions']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: instal deps
        env:
          pandoc_url: https://github.com/jgm/pandoc/releases/download/3.1.8/pandoc-3.1.8-linux-amd64.tar.gz
          pandoc: pandoc-3.1.8
          pandoc_linux: pandoc-3.1.8-linux-amd64.tar.gz

          magick_url: https://imagemagick.org/archive/binaries/magick

          ffprobe_url: https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v6.1/ffprobe-6.1-win-64.zip
          ffprobe_linux: ffprobe-6.1-linux-64.zip
        run: |
          wget $magick_url; wget $ffprobe_url; wget $pandoc_url

          unzip $ffprobe_linux
          sudo chmod +x ./ffprobe
          sudo cp ./ffprobe /usr/local/bin

          sudo chmod +x ./magick
          sudo cp ./magick /usr/local/bin

          tar -xvf $pandoc_linux
          sudo cp -r $pandoc/bin/* /usr/local/bin
          sudo cp -r $pandoc/share/* /usr/local/share

      - name: Checkout the source repository
        uses: actions/checkout@v3

      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: .tmp
          key: ${{ runner.os }}-primes

      - name: build
        run: |
          make distclean
          make build -j$(nproc)

      - name: Save Primes
        id: cache-primes-save
        uses: actions/cache/save@v4
        with:
          path: .tmp
          key: ${{ runner.os }}-primes

      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: "placeholder"
          if_key_exists: fail 

      - name: add known_hosts
        run: ssh-keyscan -p ${{ secrets.PORT }} -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: rsync over SSH
        env:
          SSH_PORT: ${{ secrets.PORT }}
          SSH_USERNAME: ${{ secrets.USERNAME }}
          SSH_HOST: ${{ secrets.HOST }}
          BUILD_PATH: ${{ secrets.BUILD_PATH }}
        run: |
          rsync -avz -e "ssh -p $SSH_PORT" dist $SSH_USERNAME@$SSH_HOST:$BUILD_PATH
