name: build

env:
  pandoc_url: https://github.com/jgm/pandoc/releases/download/3.6/pandoc-3.6-linux-amd64.tar.gz
  pandoc: pandoc-3.6
  pandoc_linux: pandoc-3.6-linux-amd64.tar.gz
  yq_url: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
  yq: yq_linux_amd64
  imagemagick_version: '7.1.1-43'

on:
  workflow_dispatch:
  push:
  workflow_run:
    workflows: ['update_webmentions']
    types:
      - completed
jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/bin/yq
            /usr/local/bin/pandoc
            /usr/local/bin/magick
            /usr/local/bin/identify
            /usr/local/share/pandoc
            ~/.imagemagick
          key: ${{ runner.os }}-deps-${{ env.imagemagick_version }}-${{env.pandoc}}-${{ hashFiles('**/lockfiles') }}

      - name: instal external deps
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          # Install build dependencies for ImageMagick
          sudo apt-get update
          sudo apt-get install -y \
            wget build-essential libpng-dev libjpeg-dev libtiff-dev \
            libwebp-dev libheif-dev libde265-dev libvpx-dev \
            libfftw3-dev libltdl-dev liblcms2-dev liblqr-1-0-dev \
            libraqm-dev librsvg2-dev libxml2-dev libghc-cairo-dev \
            libglib2.0-dev ghostscript libdjvulibre-dev libjxl-dev \
            libraw-dev libopenjp2-7-dev libwmf-dev libzip-dev \
            ocl-icd-opencl-dev opencl-headers libopenexr-dev \
            libpango1.0-dev ffmpeg perl perl-modules

          # Create required Perl directories
          sudo mkdir -p /usr/local/lib/x86_64-linux-gnu/perl/5.38.2/Image
          sudo chown -R $USER:$USER /usr/local/lib/x86_64-linux-gnu/perl

          # Download and install ImageMagick 7
          wget https://github.com/ImageMagick/ImageMagick/archive/refs/tags/${{ env.imagemagick_version }}.tar.gz
          tar xvf ${{ env.imagemagick_version }}.tar.gz
          cd ImageMagick-${{ env.imagemagick_version }}
          ./configure --prefix=$HOME/.imagemagick \
            --enable-shared \
            --disable-static \
            --with-modules \
            --enable-hdri \
            --enable-opencl \
            --with-fftw \
            --with-djvu \
            --with-webp \
            --with-heic \
            --with-rsvg \
            --with-xml \
            --with-openjp2 \
            --with-wmf \
            --with-jxl \
            --with-raw \
            --with-lqr \
            --with-openexr \
            --with-pango \
            --with-gslib \
            --with-perl \
            --with-perl-options='INSTALLDIRS=site'
          make -j$(nproc)
          make install
          sudo ln -s $HOME/.imagemagick/bin/magick /usr/local/bin/magick
          sudo ln -s $HOME/.imagemagick/bin/identify /usr/local/bin/identify
          cd ..

          # Install yq
          wget ${{ env.yq_url }}
          chmod +x ${{ env.yq }}
          sudo cp -r ${{ env.yq }} /usr/local/bin/yq

          # Install pandoc
          wget ${{ env.pandoc_url }}
          tar -xvf ${{ env.pandoc_linux }}
          sudo cp -r ${{ env.pandoc }}/bin/* /usr/local/bin
          sudo cp -r ${{ env.pandoc }}/share/* /usr/local/share

      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y wget ffmpeg

      - name: Checkout the source repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Restore cached dist
        id: cache-dist-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            dist
          key: ${{ runner.os }}-dist-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-dist-

      - name: Restore cached .tmp
        id: cache-tmp-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .tmp
          key: ${{ runner.os }}-tmp-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-tmp-

      - name: clean dist dir
        if: github.event_name == 'workflow_dispatch'
        run: make distclean

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: install node deps
        run: |
          pnpm install

      - name: build
        run: |
          set -e
          make build -j$(nproc)
          wait

      - name: post build
        run: |
          pnpm run css

      - name: Save dist cache
        id: cache-dist-save
        uses: actions/cache/save@v4
        with:
          path: |
            dist
          key: ${{ runner.os }}-dist-${{ github.sha }}

      - name: Save tmp cache
        id: cache-tmp-save
        uses: actions/cache/save@v4
        with:
          path: |
            .tmp
          key: ${{ runner.os }}-tmp-${{ github.sha }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Deploy to Coolify
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
