name: Webmentions
 
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
 
jobs:
  webmentions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
 
      - name: Fetch webmentions
        env:
          WEBMENTION_TOKEN: ${{ secrets.WEBMENTION_TOKEN }}
        run: ./bin/webmention
 
      - name: Commit to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "webmentions[bot]"
          git add .
          git diff --quiet && git diff --staged --quiet ||\
            (git commit -m "fetch webmentions"; git push origin master)
